[package]
name = "eggsecutor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
shellexpand = "2.1"
serde_json = "1.0.59"
serde = {version = "1.0.127", features = ["derive"]}
