#!/usr/bin/python3

import time
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello_world():
    return "<p>Hello, World!</p>"

def run():
    app.run()

def wait():
    time.sleep(2)

if __name__ == "__main__":
	#  run()
    wait()
